### ISSUE TITLE
Conflicting permissions handling between get_phone_number and mobile_scanner plugins causing app crash

### ISSUE THREAD

**Issue by binzheng** [ssk-flutter/get_phone_number#23]
## Summary

When using both the `get_phone_number` and `mobile_scanner` plugins in the same Flutter app, the app crashes when requesting permissions. Initially, the `get_phone_number` plugin requests permissions, which succeeds. However, when the `mobile_scanner` plugin subsequently requests permissions, the app crashes with the following error message.

## Environment

- Flutter version: 3.19.5
- Android OS version: [e.g., Android 11]
- Device: [e.g., Google Pixel 4a]
- `mobile_scanner` version: 3.5.2
- `get_phone_number` version: 3.0.10
- IDE: [e.g., Android Studio 2022.1.1]

## Steps to Reproduce

1. Launch the app.
2. Use the `get_phone_number` plugin to request permissions and grant them.
3. Then, use the `mobile_scanner` plugin to request camera permissions.
4. The app crashes, displaying the following error message.

## Expected Behavior

Both `get_phone_number` and `mobile_scanner` should successfully request permissions without causing the app to crash.

## Actual Behavior

The app crashes with the following error message when trying to request permissions using `mobile_scanner` after `get_phone_number` has already requested permissions.

## Error Message
```
E/AndroidRuntime(11603): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1926, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.xxxx.YYY_XX.GM.debug/com.xxxx.YYY_XX.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(11603): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5527)
E/AndroidRuntime(11603): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5566)
E/AndroidRuntime(11603): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(11603): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(11603): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime(11603): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime(11603): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
E/AndroidRuntime(11603): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11603): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(11603): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(11603): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(11603): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11603): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(11603): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(11603): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(11603): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime(11603): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:277)
E/AndroidRuntime(11603): 	at ssk.get_phone_number.GetPhoneNumberPlugin.onRequestPermissionsResult(GetPhoneNumberPlugin.kt:113)
E/AndroidRuntime(11603): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:746)
E/AndroidRuntime(11603): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:405)
E/AndroidRuntime(11603): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:805)
E/AndroidRuntime(11603): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:908)
E/AndroidRuntime(11603): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:9089)
E/AndroidRuntime(11603): 	at android.app.Activity.dispatchActivityResult(Activity.java:8947)
E/AndroidRuntime(11603): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5520)
E/AndroidRuntime(11603): 	... 13 more
```

**Comment by deviankim** [comment]
Thank you for your reporting. I'll check it soon.
I'm sorry for late answer.

**Comment by deviankim** [comment]
Hi binzheng,

Thank you for providing detailed feedback and raising this issue!

I’ve tested a similar scenario using the latest version of the `mobile_scanner` plugin, and I can confirm that in my setup, the issue does not occur. I wasn’t able to replicate the problem you encountered with the specific versions you mentioned, so it’s possible that updating to the latest version might resolve the issue.

I recommend updating to the most recent version of the `mobile_scanner` plugin and seeing if that resolves the crash. Additionally, I’ve tested this on a dedicated branch for this issue, which you can check out here:  
[Branch: Conflicting permissions handling between get_phone_number and mobile_scanner](https://github.com/ssk-flutter/get_phone_number/tree/test/%2323-Conflicting-permissions-handling-between-get_phone_number-and-mobile_scanner-plugins-causing-app-crash-%2323)

Here’s my test environment for reference:
- **Flutter**: 3.24.2
- **get_phone_number**: 3.0.10
- **mobile_scanner**: 5.2.2
- **IDE**: IntelliJ 2024.2.1
- **Device**: Samsung Note 20 (Android 13)

Please let me know if updating helps or if you encounter any other issues.

Best regards,

**Comment by binzheng** [comment]
Thank you for your prompt response and for checking the issue in the latest version of the mobile_scanner plugin.

I am currently using Flutter version 3.19.5, and the issue still persists with this version. Could you please test the scenario with Flutter 3.19.5 to see if the issue can be replicated? This will help us determine if the problem is specific to this version of Flutter or related to the plugin versions.

I appreciate your assistance and look forward to hearing from you.

Best regards,
Binzheng

**Comment by binzheng** [comment]
@deviankim 

Here’s my test environment for reference:

Flutter: 3.29.0
get_phone_number: 3.0.10
mobile_scanner: 4.0.0
IDE: Vs Code 1.97.2
Device: Andorid emulator(Pixel 2 API 34)

**Comment by deviankim** [comment]
> Here’s my test environment for reference:
> 
> Flutter: 3.29.0 get_phone_number: 3.0.10 mobile_scanner: 4.0.0 IDE: Vs Code 1.97.2 Device: Andorid emulator(Pixel 2 API 34)

I tested with the latest version of mobile_scanner, but I could not find any issues.

Please refer to this branch and the attached video:

https://github.com/ssk-flutter/get_phone_number/tree/example/no-conflict-with-mobile-scanner

https://github.com/user-attachments/assets/e1a0d3df-0aef-4fa6-9129-de2d2dcc0274

How about updating mobile_scanner to version ^6.0.7?

**Comment by cmd003** [comment]
I'm experiencing the same issue.
I'm using version 3.0.10, and it seems to occur after requesting location permission.
"backgroundStatus = await Permission.locationAlways.request();"
